module.exports = {
  SHOW_RESULTS_FOR_DISTRIBUTOR : 'SHOW_RESULTS_FOR_DISTRIBUTOR',
  SHOWN_RESULTS_FOR_DISTRIBUTOR: 'SHOWN_RESULTS_FOR_DISTRIBUTOR',
  HIDE_RESULTS_FOR_DISTRIBUTOR : 'HIDE_RESULTS_FOR_DISTRIBUTOR',
  HID_RESULTS_FOR_DISTRIBUTOR  : 'HID_RESULTS_FOR_DISTRIBUTOR',
  FETCH_DISTRIBUTORS_FOR_BOM   : 'FETCH_DISTRIBUTORS_FOR_BOM',
  FETCHED_DISTRIBUTORS_FOR_BOM : 'FETCHED_DISTRIBUTORS_FOR_BOM',
  FETCH_DISTRIBUTORS           : 'FETCH_DISTRIBUTORS',
  FETCHED_DISTRIBUTORS         : 'FETCHED_DISTRIBUTORS',
};
